server:
  port: 9008
  servlet:
    context-path: /cloud-rest

spring:
  application:
    name: sa-toke
  # 对出现不匹配的路径做处理
  mvc:
    #开启为找到处理器抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    # 不需要映射resources下的error目录的内容
    add-mappings: false

sa-token:
  activity-timeout: -1
  token-name: zjtoken
  is-concurrent: true
  is-log: true
  jwt-secret-key: asfztt
  # 关闭从body和cookie里面读取token,只能从请求头里面读取token,对测试不是很友好
  # 测试可以开启从cookie读取token
  is-read-body: false
  #is-read-cookie: false

