# 应用名称
#spring.application.name=cloud-provider
# 服务提供者 cluster
spring:
  application:
    name: cloud-provider

server:
  port: 9001

logging:
  level:
    root: info
    com.ztt.cloudprovider.clouddaointerface: debug







