---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangtingting.
--- DateTime: 2022/5/17 16:32
---
function main()
    print("hello lua...")
    return 2;
end


function varLocal()
    name = "my is local var(type string)";
    io.write("Length of name ",#name,"\n")
end

varLocal()